### ISSUE TITLE
Close login windows (cross button)

### ISSUE THREAD

**Issue by PastiiJ** [Nelderson/MV_Online#102]
Hi Nelderson and thank you for your hard work.

Would it be possible to add a cross button to close the login window? If the server is disconnected, I remain stuck on the connection window and this forces me to restart the game.

Thank you in advance for reviewing my question.

**Comment by squareware** [comment]
Edit the cancel button from the first login form / screen to something like this:

$("#btnCancel").bind("click touchstart",function({SceneManager.goto(MMO_Scene_Title);
});

Not sure how the save data is handled with the cloud save plugin while playing without login.

**Comment by PastiiJ** [comment]
Thank you my friend, i'll try this!!

**Comment by Nelderson** [comment]
Thanks @squareware
