### ISSUE TITLE
Derive all windows from Window_Base

### ISSUE THREAD

**Issue by MChambers1992** [Nelderson/MV_Online#11]
Currently features such as chat and login are using custom elements outside of the engine to render these input windows, this creates an inconsistency for consumers of the plugins who are expecting to be able to use their RPG Maker MV windowskins for these features. I think a useful mantra to adopt would be making sure that we are following the window style of RPG Maker meaning features such as windowskins can be applied without any issues.

**Comment by Nelderson** [comment]
I actually had this idea originally, and ended up having to scrap it.  The reality is DOM elements are already setup to handle input field logic.  When I tried to implement input fields into RPGMaker and canvas I had more problems than it was worth to fix.  

Currently I have a css file for the login (MMO.css) and I could rename and make css the standard for any changes that need to be made to any input screens going forward. 

If anyone has an idea on how to get input fields working well in MV with the Window_Base class I'm certainly not opposed to the idea :)

**Comment by MChambers1992** [comment]
Yeah I hadn't given it much thought on exact implementation but I assume that if we can access things input managers in the DOM element we should be able to grab them in the Window_base, although it might be a bit more difficult. Definitely something to consider going forward as like I say it makes managing a consistent style a bit easier.

I think this is a potential enhancement if a good enough solution could be developed.

**Comment by Nelderson** [comment]
For right now I'm going to close this, but if anyone finds resources to make this possible I'd love to hear about it.
