### ISSUE TITLE
DeprecationWarning on MongodB

### ISSUE THREAD

**Issue by ratwareid** [Nelderson/MV_Online#14]
Please update new connection script using new version of mongodb . Thank you

**Comment by MChambers1992** [comment]
This is a bug in Mongoose and will be fixed in a new version, nothing to be done other than ignore the warning until new versions are available I think. Discussed in this thread here; https://github.com/Automattic/mongoose/issues/5304

**Comment by shadowoffice** [comment]
module.exports = function(){
  var config = require('../configurations/config');
  var mongoose = require('mongoose');
  //Mongo DB Database Connection
  mongoose.connect(config.mongoDBconnect, { useMongoClient : true }  )
    .catch(err => console.error(err));
};

**Comment by CoehManeh** [comment]
Change line 7 in **_server/api_router/loginDBConnection.js_**

`mongoose.connect(config.mongoDBconnect, function(err) {`
to
`mongoose.connect(config.mongoDBconnect, { useMongoClient: true }, function(err) {`

**Comment by Titanor-Soulstone** [comment]
I had the exact same issue and that suggestion worked
