### ISSUE TITLE
Upgrade Login system and Save Cloud BUG !

### ISSUE THREAD

**Issue by ratwareid** [Nelderson/MV_Online#16]
Hey nels, i have idea to login form 👍 
First , u must add forget password to your login form
Second , u must force Game End > To Title into Game End > Logout / Exit game
The last is very important , save cloud bug.
The bug is came when u try to save to cloud with 2 player connecting with same map with u.
So this is the very important, can u fix this bug so every player can save with map when other player connecting behind him. Thank you

**Comment by Nelderson** [comment]
I already have a feature planned in issue #2 for the reset password issue.

As for the cloud save issue I'll look into it

**Comment by ratwareid** [comment]
Thanks , i will try.
