### ISSUE TITLE
Multiple logins with the same login credentials

### ISSUE THREAD

**Issue by Yoshi72** [Nelderson/MV_Online#17]
Currently the login-scripts do not check wether or not an account is already logged in and allow any new client/connection with the same login credentials.

**Comment by MChambers1992** [comment]
This is a really good point to raise I think, it might be worth adding some server side logic to check if the player account id is currently active on the server and if it is disconnecting it or preventing the additional login.

Which would people prefer, either logging out the account if it is currently logged in or preventing logging in for the user trying to use the same credentials? Either way it should be a fairly small change.

**Comment by Yoshi72** [comment]
Locking the login is a bad idea. If you happen do have a disconnect for whatever reason and the server doesn't free the connection for whatever reason you will be locked out completely. Also, the currently logged in person doesn't know about the second attempt to login with his account data. If he is being kicked from his session with a corresponding error message will make it very clear that his account might had been compromised.

So my recommendation: The second login will get a popup to choose wether or not he wants to login and kill the current connection.

**Comment by MChambers1992** [comment]
Yep that seems like the right move to make, definitely think this feature should be included.
