### ISSUE TITLE
CloudSave

### ISSUE THREAD

**Issue by shadowoffice** [Nelderson/MV_Online#18]
Hello im got error in console in whit new savecloud version 

OPTIONS /cloudsave/savetocloud 403 0.392 ms - 48

and reload page have this error : Cloudsave Failed

**Comment by Nelderson** [comment]
If you're getting a 403 error it has to do with login credentials.  Did you disable the login plugin?

**Comment by shadowoffice** [comment]
no its enable

**Comment by Nelderson** [comment]
So a 403 means forbidden from the server.  Either your api route is rejecting it because the token is invalid/not there.....or your webserver is rejecting the get/post request before it even hits my system.  Judging by your second issue I think this issue is more to do with your particular server than the plugins.

**Comment by shadowoffice** [comment]
Ok i try to install HTTPS credential in my server i respost this work

**Comment by Nelderson** [comment]
I don't think https will work...

<img width="1680" alt="screen shot 2017-08-09 at 9 41 32 am" src="https://user-images.githubusercontent.com/15018654/29124576-4be294c2-7ce7-11e7-9459-89eb332487fc.png">

There seems to be something up with your webserver in general.  And I'm more concerned about the message where the preflight has an invalid http code....

**Comment by shadowoffice** [comment]
Using 
Server version: Apache/2.4.10 (Debian)
Server built:   Jul 18 2017 18:32:16

PHP 7.0.20-1~dotdeb+8.2 (cli) ( NTS )

**Comment by shadowoffice** [comment]
have this error in console have update PHP to 7.1 and have install rewrite module in create .htacces
whit

	<IfModule mod_rewrite.c>
		RewriteEngine On
	</IfModule>

![image](https://user-images.githubusercontent.com/2808349/29127829-2a0c484e-7cf0-11e7-9439-420f5dc48447.png)

**Comment by shadowoffice** [comment]
testing on local and work for client whit maker to server WTF

**Comment by shadowoffice** [comment]
Found simply solution for allow domain 

// allow url
app.use(function(req,res,next){
	res.setHeader('Access-Control-Allow-Origin', '*');
	next();
});

**Comment by shadowoffice** [comment]
testing on another Server whit Cpanel juste Client Webserver its on this server and server socket.io on VPS
giving same error

**Comment by shadowoffice** [comment]
no idea my errror here ?

**Comment by shadowoffice** [comment]
have search few solution in internet and have so have testing on My VPS ! so nelderson have always time im testing same error 

Not work have 403 Same error :(
```


    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }


upstream websocket {
    server localhost:8000;
}

server {
    listen       80;
    server_name  localhost;
	    proxy_pass_header Set-Cookie;

     location ~ ^/(node|socket\.io) {
        proxy_pass http://websocket;
        proxy_http_version 1.1;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header Host $http_host;
         proxy_set_header X-NginX-Proxy true;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";
    	proxy_pass_header X-XSRF-TOKEN;
    }

    location /index.html {
        root   /var/www/html/;
    }


    location ~ \.css {
        root   /var/www/html;
        expires max;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|js|woff|woff2|ttf|json)$ {
        root   /var/www/html;
        access_log off;
        expires max;
    }

    location ~* \.(js|css)$ {
        expires 1y;
        log_not_found off;

    }

    location /cloudsave/loadfromcloud {
	proxy_pass http://websocket;
        proxy_http_version 1.1;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header Host $http_host;
         proxy_set_header X-NginX-Proxy true;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";
    	proxy_pass_header X-XSRF-TOKEN;
         proxy_redirect off;
    }


    location /cloudsave/savetocloud {
	proxy_pass http://websocket;
        proxy_http_version 1.1;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header Host $http_host;
         proxy_set_header X-NginX-Proxy true;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";
    	proxy_pass_header X-XSRF-TOKEN;
         proxy_redirect off;
    }

    location /cloudsave {
	proxy_pass http://websocket;
        proxy_http_version 1.1;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header Host $http_host;
         proxy_set_header X-NginX-Proxy true;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";
    	proxy_pass_header X-XSRF-TOKEN;
	 proxy_redirect off;
    }

}
```

**Comment by shadowoffice** [comment]
YEAHHHHH !!! Found Error ! Comment in few minute !
