### ISSUE TITLE
Fix... please !!!

### ISSUE THREAD

**Issue by tentran2k1** [Nelderson/MV_Online#20]
Every 3 or more players, when I open the menu or other maps, the screen is white opaque

**Comment by tentran2k1** [comment]
plugin Network_Online

**Comment by CrissNamon** [comment]
1)Open rpg_managers.js in your game plugins folder
2)On 1869 line add
`SceneManager.curr_scene = function(sceneClass){
	return this._scene.constructor == sceneClass;
}`
3)Open Online_Network_Players.js in your game plugins folder
4) On 67 line add
`if(SceneManager.curr_scene(Scene_Map)){`
5) On 95 line, after `networkMapEvents[player]._characterIndex = characterIndex;` add }

**Comment by shadowoffice** [comment]
@CrissNamon you can PR this for fix lol

**Comment by Nelderson** [comment]
This was actually an issue with the network sprites being created before the map spriteset was finished being created.   I just submitted a commit to fix it :)
