### ISSUE TITLE
Error: Cannot find module './configurations/config'

### ISSUE THREAD

**Issue by Titanor-Soulstone** [Nelderson/MV_Online#26]
hey Nelderson

I'me getting an error of "Error: Cannot find module './configurations/config'" before the server shuts down by itself

what am i doing wrong?

here is the debug log
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mvonline@0.2.2~prestart: mvonline@0.2.2
6 silly lifecycle mvonline@0.2.2~prestart: no script for prestart, continuing
7 info lifecycle mvonline@0.2.2~start: mvonline@0.2.2
8 verbose lifecycle mvonline@0.2.2~start: unsafe-perm in lifecycle true
9 verbose lifecycle mvonline@0.2.2~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Administrator\Desktop\MV_Online-master\server\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Roaming\npm
10 verbose lifecycle mvonline@0.2.2~start: CWD: C:\Users\Administrator\Desktop\MV_Online-master\server
11 silly lifecycle mvonline@0.2.2~start: Args: [ '/d /s /c', 'node server.js' ]
12 silly lifecycle mvonline@0.2.2~start: Returned: code: 1  signal: null
13 info lifecycle mvonline@0.2.2~start: Failed to exec start script
14 verbose stack Error: mvonline@0.2.2 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid mvonline@0.2.2
16 verbose cwd C:\Users\Administrator\Desktop\MV_Online-master\server
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error mvonline@0.2.2 start: `node server.js`
22 error Exit status 1
23 error Failed at the mvonline@0.2.2 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mvonline package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs mvonline
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls mvonline
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

and here is the server.js
`//=============================================================================
// Nelderson's Online Core Server
// Version: 0.2.1 - August 3rd, 2017
//=============================================================================
var express = require('express');
var app = express();
var server = require('http').Server(app);
var io = require('socket.io')(server);
var config = require('./configurations/config');
var bodyParser = require('body-parser');
var logger = require('morgan'); //For development
var socketioJwt = require('socketio-jwt');
var log = require('tracer').colorConsole(config.loggingConfig);

app.use(logger('dev'));//For development
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: false}));

server.listen(config.port);
log.info('Server is on bruh and running on port: '+ config.port);

app.use(function(req,res,next){
	res.setHeader('Access-Control-Allow-Origin', 'http://13.54.225.65:8000');
	next();
});

//----------------------------------
// SET ROUTES FOR EXPRESS API HERE:
//----------------------------------

// No Authentication required:
app.use('/',require('./api_routes/login_routes'));

// Authentication required:
app.use('/example',require('./api_routes/example.js'));
app.use('/metrics',require('./api_routes/metrics'));
app.use('/cloudsave',require('./api_routes/cloudsave.js'));

//Static Server - Used to serve static files (HTNL,PNG,etc.)
app.use('/static', express.static('public'));
//----------------------------------
// ADD SOCKET IO MODULES HERE:
//----------------------------------
var exampleSocket = require('./socket_modules/exampleSocket');
var chat = require('./socket_modules/chat');
var netplayers = require('./socket_modules/netplayer');

//Pre Socket Processes Here (Mostly for Database connections)
var loginDBConnection = require('./api_routes/loginDBConnection')();

//Authorize socket connection with token from login
io.set('authorization', socketioJwt.authorize({
  secret: config.jwtSecret,
  handshake: true
}));

//When first connected to Socket.io
io.on('connection', function(socket){
  io.clients(function(error, clients){
    if (error) throw error;
    log.info("There are " + clients.length + " players connected");
  });
});

//----------------------------------
// BIND SOCKET IO MODULES HERE:
//----------------------------------
exampleSocket(io);
chat(io);
netplayers(io);
`

**Comment by Titanor-Soulstone** [comment]
I just tested my setting on localhost and it has come up with the same error

**Comment by Nelderson** [comment]
Run a` npm install -d `

Then make sure you have a config.js file in your configurations folder

**Comment by Titanor-Soulstone** [comment]
I have already checked that in fact before i had that problem i had a problem with authenticating the database

**Comment by shadowoffice** [comment]
Normal write this on server.js 
//----------------------------------
// Cors ;
//----------------------------------

var allowCrossDomain = function(req, res, next) {
res.header('Access-Control-Allow-Origin', '*');
res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
res.header('Access-Control-Allow-Headers', 'Content-Type, x-access-token');
if (req.method === "OPTIONS")
res.send(200);
else
next();
}

//----------------------------------
// SET ROUTES FOR EXPRESS API HERE:
//----------------------------------

// Allow cors
app.use(allowCrossDomain);

**Comment by Titanor-Soulstone** [comment]
i just tired that one, and it still did not work, this problems becoming a real head scratcher

**Comment by shadowoffice** [comment]
what error you have on console ?

**Comment by Titanor-Soulstone** [comment]
`Error: Cannot find module './configurations/config'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\MV_Online-master\server\api_routes\metrics.js:6:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\MV_Online-master\server\server.js:53:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mvonline@0.2.2 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mvonline@0.2.2 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mvonline package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mvonline
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mvonline
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\Desktop\MV_Online-master\server\npm-debug.log`

**Comment by Titanor-Soulstone** [comment]
the same error also appears on my localhost test server

**Comment by shadowoffice** [comment]
check your server config metric API

**Comment by Titanor-Soulstone** [comment]
what file exactly am i looking for

**Comment by Titanor-Soulstone** [comment]
is it metrics.js under api_routes

**Comment by Titanor-Soulstone** [comment]
ok i think i might have figured it out because i am also having a cannot bind to port error on my other servers on amazon aws

**Comment by Titanor-Soulstone** [comment]
ok, I fixed the port problem but i am still having trouble with the mv server with the exact same error

**Comment by Titanor-Soulstone** [comment]
can anyone help me?

**Comment by Titanor-Soulstone** [comment]
it is saying something about a module.js, what is that about?

**Comment by CoehManeh** [comment]
I also have the same problem, but when I put the code below and server dont run.

`app.use('/metrics',require('./api_routes/metrics'));`

**Comment by Titanor-Soulstone** [comment]
Alright! the  server is up and running, I cannot believe it was the metrics system that was causing it
