### ISSUE TITLE
/activate/ error 404

### ISSUE THREAD

**Issue by Titanor-Soulstone** [Nelderson/MV_Online#27]
hey Nelderson, I am getting an error of
`Cannot GET /activate/`
on the HTML/HTTP side and on the server side an error of 
`GET /activate/ 404 0.218 ms - 148`.
do you have any idea on how to fix this?

**Comment by Nelderson** [comment]
Make sure this is in your server: 

app.use('/',require('./api_routes/login_routes'));

404 means the route is not there....

**Comment by Titanor-Soulstone** [comment]
it is already in there, but just to make sure I have done it right, is this how the code is meant to look
`// Allow cors
app.use(allowCrossDomain);

// No Authentication required:
app.use('/',require('./api_routes/login_routes'));

// Authentication required:
app.use('/example',require('./api_routes/example.js'));
//app.use('/metrics',require('./api_routes/metrics'));
app.use('/cloudsave',require('./api_routes/cloudsave.js'));
'

**Comment by shadowoffice** [comment]
same here new patch fix this 
```
var allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
    res.header('Access-Control-Allow-Headers', 'Content-Type, x-access-token');
    if (req.method === "OPTIONS") 
        res.send(200);
    else 
        next();
}
```

**Comment by Titanor-Soulstone** [comment]
I already have that in there and I am still having the problem.

**Comment by Titanor-Soulstone** [comment]
ok i dont know what i did but i somehow fixed it
