### ISSUE TITLE
Login Core Error Client Side

### ISSUE THREAD

**Issue by Titanor-Soulstone** [Nelderson/MV_Online#28]
Hey Nelderson, I am getting an error on my game client of
`ReferenceError
$ is not defined`
whenever I add the login core.
do you know how to fix this?
the same error also occurs on save or new file load with the plugin Online Chat

**Comment by Titanor-Soulstone** [comment]
the same error also occurs on save or new file load with the plugin Online Chat

**Comment by CoehManeh** [comment]
Change your index.html code for code of sampleindex.html from location /game_resources/sampleindex.html in your project.

**Comment by Titanor-Soulstone** [comment]
ok, I just changed that now I'm getting the error
`Error
Uncaught SynjtaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin 'undefined' in a call to postMessage'`

**Comment by shadowoffice** [comment]
for this error 
var allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
    res.header('Access-Control-Allow-Headers', 'Content-Type, x-access-token');
    if (req.method === "OPTIONS") 
        res.send(200);
    else 
        next();
}

**Comment by Titanor-Soulstone** [comment]
I already have that on the Server side, this was a client-side error. anyway I fixed it because I discovered there was an issue with another plugin being enabled with this plugin enabled

**Comment by rafaelrodrigosilveira** [comment]
Hello. I have the same error, and where I have the put this code above?
