### ISSUE TITLE
Accountnames and Characternames

### ISSUE THREAD

**Issue by KevinAT** [Nelderson/MV_Online#30]
since there was a bit of discussion about how usernames should be solved, especially given that players could abuse the system and have dozens of characters with the same name, i'd like to share my thoughts on this. how about making it like this:

have each user register with an email (that also counts as the account name) and a password. send registration code to email, allow user to change email and password later on yada yada..

in-game there will probably be those kinds of games:

players barely interact with each other so a simple username is ok for identification and metrics; usernames don't have to be "roleplayish";

mmorpg like where lots of players have characters and interact with each other; each name will have to be unique, but some players will also want to have roleplayish names;

players interact a lot with each other in a probably somewhat fixed story; can't change names and has to chose pre defined characters with names; since those games will probably have limited multiplayer features and will be more like party games for friends it won't be neccessary to differentiate between lots of players

so the best thing to do would be to let game makers decide on whether players can chose a name for their account, or whether they have to select (a pre defined character with) a name. possibly even allow them to let players have the same names (after all the server can still identify them based on email)

i think it should also be possible to set rules for custom user names, like swear word dictionaries, uniqueness, only letters, or maybe you have to chose a first and a last name (allow spaces), etc.

something else i think would be great is: some mmos allow players to have multiple characters without the need for seperate accounts; allow game makers to have multiple characters/usernames on one account/email-adress.

**Comment by MChambers1992** [comment]
All these ideas are possible through plugins definitely, it would be down to individual developers to implement these options I think as to consider so many options in the base functionality is quite a hefty task and there will also be cases people want that aren't implemented. The best option for the base plugin in my opinion is a simple implementation like it has now and then if developers want to extend this, they can.

**Comment by Nelderson** [comment]
I also agree it's up to the individual developer to choose these types of options.
