### ISSUE TITLE
Connecting Issues

### ISSUE THREAD

**Issue by gamernickk** [Nelderson/MV_Online#34]
Hello,
I can connect to my server via the Desktop export.
But not via the web export.

Why? 
I forwarded the ports, could this be a issue?

-EDIT-
Here is a image showing:
https://imgur.com/a/dUttD
left is my website, right is the client. Both on the same version.

-Another EDIT-
Okay, so I noticed my server is saying the /login and /register etc.
But nothing happens in the client.

**Comment by Nelderson** [comment]
Do me a favor and go into your browser console and see if there are any errors....I haven't used opera with this project before.

**Comment by gamernickk** [comment]
Hello, 
thanks for the reply.
Here are the errors.. https://imgur.com/a/PmUE5
Ive also tried it on chrome. And it doesnt work also.

**Comment by Nelderson** [comment]
Looks like there are 2 separate issues going on here:

1. You're calling a non SSL route over an SSL connection (HTTPS).  The only way to fix this is to use the non SSL version of your site or to add an SSL cert to socket.io and use a secure connection.  I haven't gone over how to do this yet, but it's coming in a video soon.

2. Game_Network not defined has something to do with the Main Online Core plugin file.  Make sure you're on the latest version in the game_resources folder.

**Comment by gamernickk** [comment]
I've downloaded a new copy of the Main Online Core plugin.
But it still didnt fix the error :(

For the 1st problem, I'l wait for your video.
Thanks in advance! 👍

**Comment by shadowoffice** [comment]
Have Fix this probleme whit my script ...
