### ISSUE TITLE
Uhm.. Unable To Connect My Domain

### ISSUE THREAD

**Issue by HowToDoThis** [Nelderson/MV_Online#36]
I Use The Method From The Nelderson 
```
 app.use(function(req,res,next){
	res.setHeader('Access-Control-Allow-Origin', 'https://howserver.ddns.net/');
	next();
});

```
and This Code From shadowoffice
```
var allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
    res.header('Access-Control-Allow-Headers', 'Content-Type, x-access-token');
    if (req.method === "OPTIONS") 
        res.send(200);
    else 
        next();
}
```
But Still Display This https://imgur.com/a/CHKLN 
Left is Client Right Is Console.
server.js ------> https://hastebin.com/ohesedemif.php
config.js -----> https://hastebin.com/ehucijaren.scala

Console Running As Ubuntu Server 16.04.2 LTS & NodeJS v8.7.0 (lastest) and NPM v5.4.2

**Comment by shadowoffice** [comment]
place my code on line 21 and add line 25 app.use('AllowCrossDomain');

**Comment by HowToDoThis** [comment]
@shadowoffice The Problems Still Didn't Solve After Changed To Line 21 and Added That Line 25. Still Stucks On Connecting.
The Changed Server.js Code ------------> https://hastebin.com/aqiruzuven.php

**Comment by shadowoffice** [comment]
ok now change     app.use('allowCrossDomain');                    <------------ And This is Line 25 Added app.use('allowCrossDomain');

this line on line 34 juste on top of // No Authentication required:
app.use('/',require('./api_routes/login_routes'));

**Comment by shadowoffice** [comment]
var allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
    res.header('Access-Control-Allow-Headers', 'Content-Type, x-access-token');
    if (req.method === "OPTIONS") 
        res.send(200);
    else 
        next();
}

//----------------------------------
// SET ROUTES FOR EXPRESS API HERE:
//----------------------------------
// allow url
app.use(allowCrossDomain);
