### ISSUE TITLE
Problem connecting to Android

### ISSUE THREAD

**Issue by nowsfeky** [Nelderson/MV_Online#37]
Hello Nelderson. Only the desktop version works and on localhost. If you try to use it on your mobile phone with wi-fi it is not working and it will be locked on the screen of the image that I sent. I await your help.

In the image below you have an error example using the Droid4X android emulator.
The error only happens if you try to use with android.

`https://i.imgur.com/DpMveXt.png`

**Comment by MChambers1992** [comment]
Have you enabled outside connections to your local machine? If not connections such as the Android phone (even an emulator) won't be able to connect. The best situation to test this is to host externally on something like Heroku or DigitalOcean and try to connect from both devices again.

**Comment by nowsfeky** [comment]
Hi. Could you tell me how to activate the external connection.
Maybe I'm doing it wrong or I do not know how to do it.

**Comment by MChambers1992** [comment]
Unfortunately this isn't a simple explanation as I would need to know your current network setup, the relevant part of the readme would be the last section if you have this in theory the server will allow outside connections but unless your machine the server is running on allows external connections is a separate thing.

I'd advise reading up on how to allow external connections to your machine, maybe follow a tutorial on how to connect to a simple node.js server from your phone and then the knowledge should be transferable to this situation.

**Comment by shadowoffice** [comment]
You need simply add my script on your server ;)

**Comment by shadowoffice** [comment]
var allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
    res.header('Access-Control-Allow-Headers', 'Content-Type, x-access-token');
    if (req.method === "OPTIONS") 
        res.send(200);
    else 
        next();
}

//----------------------------------
// SET ROUTES FOR EXPRESS API HERE:
//----------------------------------
// allow url
app.use(allowCrossDomain);

**Comment by nowsfeky** [comment]
OK. I was able to tidy up and connect now.
Thanks a lot for the help.
