### ISSUE TITLE
Server console says 2 players connected but cant see him.

### ISSUE THREAD

**Issue by towwi** [Nelderson/MV_Online#39]
So i set my server using aws. I deployed my game and hit the game.exe launcher and sent this deployed version to my friend too and we both did get to game and play but didnt see each other. Server said 2 players are connected. When i try to launch from index and play it on web browser it says: missing data: map002.

Does anyone have idea what im doing wrong? Do i need to set cloudsave first or something? 
And is there a difference to make game work on web browser and from game.exe on your desktop?
Im kinda stuck so if anyone have something in mind that could help please say it :P Thanks

**Comment by shadowoffice** [comment]
Hiya please give your server.js for what your have coding for config and ur maps002 lost its your game have problème its not MV_online or you have not enter the embed code on readme

**Comment by towwi** [comment]
[server stuff.zip](https://github.com/Nelderson/MV_Online/files/1472957/server.stuff.zip)

Do you need something else? i changed passwords and mails tho. Thanks for trying to help!

**Comment by shadowoffice** [comment]
you have wrong setup your server.js

**Comment by towwi** [comment]
Hmm.. Well do you have any idea what to do next to get it working? Im kinda new to these things and dont know what to do :P

**Comment by shadowoffice** [comment]
`//=============================================================================
// Nelderson's Online Core Server
// Version: 0.2.1 - August 3rd, 2017
//=============================================================================
var express = require('express');
var app = express();
var server = require('http').Server(app);
var io = require('socket.io')(server);
var config = require('./configurations/config');
var bodyParser = require('body-parser');
var logger = require('morgan'); //For development
var socketioJwt = require('socketio-jwt');
var log = require('tracer').colorConsole(config.loggingConfig);

app.use(logger('dev'));//For development
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: false}));

server.listen(config.port);
log.info('Server is on bruh and running on port: '+ config.port);

//----------------------------------
// SET ROUTES FOR EXPRESS API HERE:
//----------------------------------
// app cors
app.use('AllowCrossDomain',require('./api_routes/cors'));

// No Authentication required:
app.use('/',require('./api_routes/login_routes'));

// Authentication required:
app.use('/example',require('./api_routes/example.js'));

//Static Server - Used to serve static files (HTNL,PNG,etc.)
app.use('/static', express.static('public'));

// cloudsave
app.use('/cloudsave',require('./api_routes/cloudsave.js'));


//----------------------------------
// ADD SOCKET IO MODULES HERE:
//----------------------------------
var exampleSocket = require('./socket_modules/exampleSocket');

//Pre Socket Processes Here (Mostly for Database connections)
var loginDBConnection = require('./api_routes/loginDBConnection')();

//Authorize socket connection with token from login
io.set('authorization', socketioJwt.authorize({
  secret: config.jwtSecret,
  handshake: true
}));

//When first connected to Socket.io
io.on('connection', function(socket){
  io.clients(function(error, clients){
    if (error) throw error;
    log.info("There are " + clients.length + " players connected");
  });
});

// netplayer
var netplayers = require('./socket_modules/netplayer');
// chat
var chat = require('./socket_modules/chat');


//----------------------------------
// BIND SOCKET IO MODULES HERE:
//----------------------------------
exampleSocket(io);
netplayers(io);
chat(io);`

**Comment by towwi** [comment]
Hey again! I tested this new server.js file and now when i login to game it works fine, but when my friend logs in my game crashes, then when i log in friends game crashes? I send you a picture what it looks like when it happens. Thx alot for your time!
![crash](https://user-images.githubusercontent.com/33609447/33150450-2ac9af76-cfdc-11e7-86bc-46210d8fd3fe.JPG)

**Comment by towwi** [comment]
Nvm.. got it working just created the map002 again and it worked!

**Comment by MarStarck** [comment]
I met the same problem as you show in the picture. Do you know how to see error logs in client side?
