### ISSUE TITLE
Conection Error

### ISSUE THREAD

**Issue by rafaelrodrigosilveira** [Nelderson/MV_Online#41]
Hello,

When I do a local connection, it's work. But when I do a remote conection, don't work and appear this error, how as imagem attached.

I need your help.

Thanks
![erro](https://user-images.githubusercontent.com/3218055/33099573-73e93e7c-cef8-11e7-8f88-c5c341997d84.png)

**Comment by Nelderson** [comment]
So the reason for this is socket.io is not loading.  You need to change the url in your index.html folder to the place you have your socket server on.

**Comment by rafaelrodrigosilveira** [comment]
But I have been changed this. My index.html url is my IP. They connect, but happen this.
