### ISSUE TITLE
TypeError: this.setTextOptions is not a function

### ISSUE THREAD

**Issue by tentran2k1** [Nelderson/MV_Online#44]
rpg_managers.js:1954 TypeError: this.setTextOptions is not a function
    at Game_Player.refresh (Online_Network_Players.js:190)
    at Game_Player.refresh (

Hm.....

**Comment by Nelderson** [comment]
This was an oversight on my end.  Thanks for pointing it out!

I also added the Nasty_Text_Pop_Events.js to the plugins folder.  You can use that to see network players names above their head.
