### ISSUE TITLE
CloudSave 

### ISSUE THREAD

**Issue by tentran2k1** [Nelderson/MV_Online#47]
POST /cloudsave/savetocloud 413 34.383 ms - 2182
PayloadTooLargeError: request entity too large
        at readStream (C:\Users....\server\node_modules\raw-body\index,js:155:17)
at readStream (C:\Users....\server\node_modules\raw-body\index,js:155:12)
...
...
...
...

**Comment by Nelderson** [comment]
Alrighty.....so body parser has a built in limit for file size.  It's 100kb by default.  To change this number go into server.js and change this on line 19:

`app.use(bodyParser.urlencoded({extended: false}));`

To this:

`app.use(bodyParser.urlencoded({extended: false, limit:'500kb'}));`

You can also use mb and gb, but I would be wary of setting this limit too high.

**Comment by DatTranPro** [comment]
What happens if I set too high ?

**Comment by Nelderson** [comment]
I've seen save files get corrupt and be really huge.  If you set your limit to something high like 1gb and your database only has 500 mb it could end up badly for some people.   

It's more of a suggestion than an absolute rule :)

**Comment by DatTranPro** [comment]
rpg_managers.js:373 Data save too big 
DataManager.saveGameWithoutRescue @ rpg_managers.js:373
:3000/cloudsave/savetocloud Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by DatTranPro** [comment]
Please help me on this issue, every time I use my project for more than 5 minutes, will not save the data successfully, it will show error 404 on the command pront, please help me with :(

**Comment by tentran2k1** [comment]
What do you think about DatTranPro's problem?
- Nelderson

**Comment by Nelderson** [comment]
From what I see we have 3 issues here....each with their own set of answers...

1. rpg_managers.js:373 Data save too big - RPGMaker has a built in limit of 200kb.  I have multiple save files of games over an hour that are like 13KB total.  If you are hitting this limit one of your other plugins has to be causing the file sizes to get larger than they're supposed to be.  Does your game freeze when saving?  What are the file sizes of the save data in the save folder?

2. Failed to load resource: the server responded with a status of 403  - This means the server didn't accept the token.  Which I have personally not seen unless you aren't signing in first.  Let me know if this is the exact issue you see after that 5 minute mark.

3. error 404 on the command prompt - This means it can't find the api call and your server is setup wrong.  Verify whether it's the 403 or 404 code being sent.

**Comment by Nelderson** [comment]
Also #55 sounded exactly the same so I came out with a config option to change the token expiry time in commit 347e0a3

**Comment by DatTranPro** [comment]
Why do you need an expired token ?, if the limit token is set too long, what happens?
