### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by DatTranPro** [Nelderson/MV_Online#48]
how can i change the address to (115. ****: 8000/static/project) become address to *( ***.tk) my ?
I have edited the cors.js config file but nothing changed

**Comment by shadowoffice** [comment]
euhh yeah whit DNS services

**Comment by DatTranPro** [comment]
Can you give me detailed instructions?

**Comment by shadowoffice** [comment]
ahhh your go to your zone DNS setup your domaine A to IP
and you wait few minute for dns 
and for select your ****.tk juste change IP to domain.tk on server and client plugins 

exemple in server
domain.tk: 8000
and in client
domain.tk: 8000/static/project

**Comment by DatTranPro** [comment]
I currently have a domain name on my address.
Now I have to set up so?

Setup " Online Main Core "
Domain.tk:8000/static/project

Edit file Index.html 
"src="http://Domain.tk:8000/socket.io/socket.io.js"

Edit Config Cors.js
MyCorsHost: 'Domain.tk',

Done ?

**Comment by shadowoffice** [comment]
On Server config server/configurations/config.js
 actUrl: 'http://localhost:8000/activate/',

On Cors let *

MyCorsHost: '*',  this allow all domain to connect you can change to your domaine if you want juste on domaine  exemple 
MyCorsHost: 'mydomaine.tk',

on client 
its juste 

and on plugin 
 	Online_Network_Players.js generate paramater on your project 
for  domain.tk: 8000/static/

**Comment by DatTranPro** [comment]
Ok, thanks

**Comment by tentran2k1** [comment]
I think you should write a guide on "readme Cors" to make it easier for others to understand
- shadowoffice -

**Comment by shadowoffice** [comment]
Yeah can write tomorrow 👍

**Comment by tentran2k1** [comment]
There are some things I do not understand here.
In my domain "AAA.tk:3000/static" it works, but at "AAA.tk" it does not work
Hm....

**Comment by shadowoffice** [comment]
yeah normaly you use statics files dont use statics for alloweds domain.tk/

**Comment by tentran2k1** [comment]
haha, how to fix it?

**Comment by shadowoffice** [comment]
you can use Nginx config have creating on isssus on write your project on nginx

**Comment by tentran2k1** [comment]
i think so

**Comment by DatTranPro** [comment]
Wow,previously I had intended to use nginx to boost performance for my project, but I do not know how to set it up on the Nelderson MV_Online project.
Can you guide me to finish it okay brother?

**Comment by tentran2k1** [comment]
Do you live in Vietnamese ? DatTranPro

**Comment by shadowoffice** [comment]
@DatTranPro check this issus  #18

**Comment by tentran2k1** [comment]
Can you show me through your project?

**Comment by DatTranPro** [comment]
can you send me your project okay?, i need to look over it to understand more :(, since i have no experience on things like this

**Comment by shadowoffice** [comment]
euhh dont give my project sorry its beta of my game personal 👎

**Comment by DatTranPro** [comment]
ohh, i will try to finish it

**Comment by tentran2k1** [comment]
This is the default file of nginx.conf, can you edit it to work on MV Online project help me?


#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}
