### ISSUE TITLE
Update Plugin " Status Sytem "

### ISSUE THREAD

**Issue by ToneLove** [Nelderson/MV_Online#50]
Your project is really great, and I think there are still holes in plugins like "2 people can not see a common event, ie even though player A picks up the chest, but player B still picks up be the chest"
And it would be even better if we could fight together: D

**Comment by Nelderson** [comment]
You're thinking about global switches and variables, and it's planned to come out shortly :)

And PVP has been suggested many many times.....I'll try my beast to get around to it.
