### ISSUE TITLE
Update Online_Chat

### ISSUE THREAD

**Issue by tentran2k1** [Nelderson/MV_Online#57]
Can you make Online Chat display message on player's head instead of right in chat room? like Nasty_Pop_Eent

**Comment by Nelderson** [comment]
I have no plans to make this.   If someone wants to make an add-on I wouldn't be opposed to putting it in the project :)

**Comment by tentran2k1** [comment]
When other players send messages, others receive a message or something that allows them to open the chat ... This will help others use more of Online_Chat.

**Comment by tentran2k1** [comment]
Notify when new messages are received
