### ISSUE TITLE
TypeError: Cannot read property of 'refresh' of null

### ISSUE THREAD

**Issue by Titanor-Soulstone** [Nelderson/MV_Online#59]
Hey Nelderson
I get this error when I enable Online_Network_Players

`TypeError`
` Cannot read property of 'refresh' of null`
![capture](https://user-images.githubusercontent.com/5416652/34979566-a3e3c614-fadc-11e7-9c01-a627fcc49647.PNG)

Do you know of any way to fix this

note: I have updated both the server and client today

**Comment by Nelderson** [comment]
Give me the console output when you get the chance (F8)

**Comment by Titanor-Soulstone** [comment]
![capture2](https://user-images.githubusercontent.com/5416652/35079725-431e4f52-fc44-11e7-8e8e-0e2ca8cbf1a3.PNG)

**Comment by Nelderson** [comment]
This was happening because of SRDs plugin.  Luckily it was a straightforward fix, and it makes my plugin more compatible anyway.

Thanks again for getting the info I needed :)
