### ISSUE TITLE
Other Players not Appearing on map

### ISSUE THREAD

**Issue by Titanor-Soulstone** [Nelderson/MV_Online#60]
I have come upon a problem where other players do not appear on the map

here are the settings
`Net Player Map ID = 3`
`Net Player Event ID = 1`
`Show Username or Character Name = 0`
`Show Name Above Players Head = true`
`Player Text Options = 1`
`Net Player Text Options = 1`

here is the test run
![test](https://user-images.githubusercontent.com/5416652/35135062-8a63b466-fd15-11e7-8e22-8214620bc9d8.PNG)

**Comment by Titanor-Soulstone** [comment]
It has been 20 days and i am still looking for a solution may i please get some help on this

**Comment by Nelderson** [comment]
Other players appear on my maps just fine in multiple projects.  Do you have any other plugins that effect player movement?

**Comment by Titanor-Soulstone** [comment]
here is a list of the plugins i have installed in the order they are installed

Online_Main_Core
Online_Metrics
Online_Network_Players
Online_Chat
Online_Login_Core
Online_Cloudsave
Nasty_Text_Pop_Events
Online_GlobalVars
TelniaComputer
YEP_CoreEngine
YEP_ButtonCommonEvents
KeyboardConfig
SOUL_LootCrate
YEP_ItemCore
YEP_X_AttachAugments
YEP_X_ItemDurability
YEP_BattleEngineCore
YEP_QuestJournal
YEP_X_MoreQuests1
YEP_X_MoreQuests2
YEP_ShopMenuCore
YEP_X_MoreCurrencies
YEP_PartySystem
YEP_ClassChangeCore
YEP_ItemSynthesis
YEP_X_Subclass
YEP_MainMenuManager
YEP_GabWindow

and that is all the plugins i have enabled

**Comment by shadowoffice** [comment]
Yep core its not coded for Mv_online and many probleme in game whit this plugins whit MV_online

**Comment by Nelderson** [comment]
Nothing should be overwriting the plugins....I would need a demo to see why it's not working on yours.

**Comment by Titanor-Soulstone** [comment]
And how would I fix the problem with the Yanfly engine?

**Comment by Titanor-Soulstone** [comment]
http://13.54.225.65/telnia/ for the playtest
and the folder is at
https://mega.nz/#F!GhA2BByL!1qzpMo_hYSL5yhU-3VVV7A

**Comment by Titanor-Soulstone** [comment]
Sorry if the server doesn't work
the pc crashed yesterday and I have to reset the server.

**Comment by Nelderson** [comment]
Yeah....tried to download it and mega sucks.  Send me an email with a better link:
neldersongaming@gmail.com

**Comment by Titanor-Soulstone** [comment]
I have sent you the link via Gmail have you received it yet?

**Comment by Nelderson** [comment]
So the only plugin that's incompatible is the TelniaComputer plugin which you made.  If you disable it the network players run just fine with all those other plugins.  The reason why is because you tried to use an alias, but instead overwrote the Scene_Map start method.

Since this is an issue only for you and a specific plugin you created I'm closing this.
