### ISSUE TITLE
Development Variable & Switch

### ISSUE THREAD

**Issue by tentran2k1** [Nelderson/MV_Online#61]
add, variable = playerid, this will make the game closer to the MMO Server category,
For example, limit 5 players in a map, if one person loses connection or leaves the current map, another participant will be able to join.

**Comment by Nelderson** [comment]
1. variable = playerid is already doable => $gameVariables.setValue(varId, playerId);

2. Limiting 5 players to a map would have to be an entire separate module that the server handles.  I will put this on the list of possible upgrades, but I can't guarantee I'll get to it anytime soon.

**Comment by tentran2k1** [comment]
yeah, good idea
