### ISSUE TITLE
Global_Switches and Global_Variables

### ISSUE THREAD

**Issue by Soubi92** [Nelderson/MV_Online#65]
Is there a possibility to make Switches and Variables Offline and Online(Global)?

I mean, Switch 0 - 500 Offline not Global and Switch 500 - x Online(Global). I think its a Good Idea for Chest or Storyevents with Switches thats Offline, not all Global?

**Comment by Titanor-Soulstone** [comment]
I believe Nelderson says something about that in this youtube video
[Development Series - Global Variables 3](https://www.youtube.com/watch?v=P-o2CGWtAaY&t=169s)

**Comment by tentran2k1** [comment]
good idea
