### ISSUE TITLE
server not working after windows crash

### ISSUE THREAD

**Issue by Titanor-Soulstone** [Nelderson/MV_Online#68]
hey Nelderson

I am having trouble with the server after a blue screen of death
and I was wondering if there is a fix for it 
I have tried resetting the server

these are the settings I am using

  //---------------------
  //Login Configurations
  //---------------------
  
  //Needs to be the same as Client firstHash
  firstHash: 'PublicServerTelnia',
  
  //Mail to send activation codes from
  mailFrom: 'smtps://telnianlegends.noreply@gmail.com:<password i use>@smtp.gmail.com',
  
  //Activation API Location
  actUrl: 'https://13.54.225.65:8000/activate/',
  
  //Time until token expires (in minutes)
  tokenExpiresIn: 2880,
  
  //Allows only one logged in user at a time.
  enforceOneUser: true,
  
  //Temporary Password Complexity for lost Passwords
  lostPasswordComplexity: 2,
  
  //Temporary Password Expiration in Milliseconds
  tempPasswordExpires: 3600000, //1 hour
  
  //------------------------
  //Database Configurations
  //------------------------
  
  mongoDBconnect: 'mongodb://localhost:27017/mmodata'
};

it is connecting to google chrome ok but it won't connect to RPG maker mv
neither will it send emails

note: I am using Amazon AWS so I had to recreate the machine

**Comment by Titanor-Soulstone** [comment]
ok so now instead of not working at all it now gives 404 error for both register and login.

**Comment by Titanor-Soulstone** [comment]
ok so here is a log

GET /login 203 4.485 ms - 2
GET /logins 404 1.915 ms - 145
GET /register 403 0.587 ms - 2
GET /registers 404 0.475 ms - 148
POST //login 404 18.602 ms - 146
POST //register 404 0.674 ms - 149

**Comment by Titanor-Soulstone** [comment]
ok so i changed /login to login in the client code and here is the new log

GET /login 203 4.485 ms - 2
GET /logins 404 1.915 ms - 145
GET /register 403 0.587 ms - 2
GET /registers 404 0.475 ms - 148
POST //login 404 18.602 ms - 146
POST //register 404 0.674 ms - 149
POST /login 203 12.544 ms - 26
POST //register 404 0.388 ms - 149

**Comment by Titanor-Soulstone** [comment]
ok, so it turned out to be a client-side issue so that is that.

**Comment by Titanor-Soulstone** [comment]
ok so it was not client side because cloudsave and the others wont work either

**Comment by Titanor-Soulstone** [comment]
ok so just downloaded new client-side from GitHub a few seconds ago and it works

**Comment by Titanor-Soulstone** [comment]
just did a test run and the chat does not work

**Comment by Nelderson** [comment]
203 error can be many things.  It usually should return on your client the error associated with it.  

As for 404 errors:
Make sure the require statements and io is bound correctly (See documentation).   It all works just fine on my end...

404 errors means that you never added the routes/sockets to your server.js file.  

Should look like this somewhere in your server.js file.

```
//Somewhere in io section:
var chat = require('./socket_modules/chat');
// Somewhere at the bottom:
chat(io)
```

**Comment by Titanor-Soulstone** [comment]
ok just did a second test run and login does not connect

**Comment by Titanor-Soulstone** [comment]
203 means it is successful and here is the server.js

//----------------------------------
// SET ROUTES FOR EXPRESS API HERE:
//----------------------------------

// No Authentication required:
app.use('/',require('./api_routes/login_routes'));

// Authentication required:
app.use('/example',require('./api_routes/example.js'));
app.use('AllowCrossDomain',require('./api_routes/cors'));
app.use('/cloudsave',require('./api_routes/cloudsave.js'));
app.use('/metrics',require('./api_routes/metrics'));

//Static Server - Used to serve static files (HTNL,PNG,etc.)
app.use('/static', express.static('public'));
//----------------------------------
// ADD SOCKET IO MODULES HERE:
//----------------------------------
var exampleSocket = require('./socket_modules/exampleSocket');
var chat = require('./socket_modules/chat');
var globalvar = require('./socket_modules/globalvar');
var netplayers = require('./socket_modules/netplayer');

//Pre Socket Processes Here (Mostly for Database connections)
var loginDBConnection = require('./api_routes/loginDBConnection')();

//Authorize socket connection with token from login
io.set('authorization', socketioJwt.authorize({
  secret: config.jwtSecret,
  handshake: true
}));

//When first connected to Socket.io
io.on('connection', function(socket){

  if(config.enforceOneUser){
    var username = socket.client.request.decoded_token.name;
    if (loggedInUsers[username]){
      socket.to(loggedInUsers[username]).emit('firstShutDown',{});
      socket.emit('secondShutDown',{});
      io.of('/').connected[loggedInUsers[username]].disconnect(true);
      socket.disconnect(true);
    }else{
      loggedInUsers[username] = socket.id;
    }
  }

  io.clients(function(error, clients){
    if (error) throw error;
    log.info("There are " + clients.length + " players connected");
  });

  socket.on('disconnect',function(data){
    loggedInUsers[username] = null;
  });
});

//----------------------------------
// BIND SOCKET IO MODULES HERE:
//----------------------------------
exampleSocket(io);
chat(io);
globalvar(io);
netplayers(io);

**Comment by Titanor-Soulstone** [comment]
here is the new log since it stopped working

08:02:43.41 <INFO> There are 1 players connected
GET /cloudsave/loadfromcloud 200 2.160 ms - 37192
POST /login 200 404.857 ms - 267
GET /cloudsave/loadfromcloud 403 0.908 ms - 59
GET / 203 0.225 ms - 2
GET / 203 0.175 ms - 2
GET /nice%20ports%2C/Tri%6Eity.txt%2ebak 404 1.314 ms - 174
OPTIONS / 200 0.618 ms - 8
GET / 203 0.171 ms - 2
GET http://clientapi.ipip.net/echo.php?info=20180218204359 404 0.364 ms - 147
GET / 203 0.165 ms - 2
GET / 203 0.157 ms - 2
GET / 203 0.167 ms - 2
GET http://clientapi.ipip.net/echo.php?info=20180221164548 404 0.209 ms - 147
POST /login - - ms - -
POST /login - - ms - -
POST /login - - ms - -
GET / 203 0.175 ms - 2
GET / 203 0.154 ms - 2
GET / 203 0.154 ms - 2
POST /login - - ms - -
POST /login - - ms - -
POST /login - - ms - -
POST /login - - ms - -
POST /login - - ms - -
POST /login - - ms - -
GET /favicon.ico 404 0.200 ms - 150
GET / 203 0.228 ms - 2
GET / 203 0.244 ms - 2

**Comment by Titanor-Soulstone** [comment]
here is the log so far

21:55:11.09 <INFO> Server is on bruh and running on port: 8000
POST /login 200 443.008 ms - 267
21:55:16.32 <INFO> There are 1 players connected
express deprecated req.param(name): Use req.params, req.body, or req.query instead authenticateAPI.js:7:36
GET /cloudsave/loadfromcloud 200 31.013 ms - 10
(node:10040) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
POST /cloudsave/savetocloud 200 566.183 ms - -
POST /cloudsave/savetocloud 200 561.531 ms - -
POST /login 200 403.899 ms - 267
22:06:38.20 <INFO> There are 1 players connected
GET /cloudsave/loadfromcloud 200 2.676 ms - 37192
POST /register 200 417.109 ms - 78
22:07:37.73 <INFO> { accepted: [ 'sir.titas@yahoo.com.au' ],
  rejected: [],
  envelopeTime: 1168,
  messageTime: 1186,
  messageSize: 1272,
  response: '250 2.0.0 OK 1518876457 o26sm14612041edi.18 - gsmtp',
  envelope:
   { from: 'no-reply@myserver.com',
     to: [ 'sir.titas@yahoo.com.au' ] },
  messageId: '<c29278db-3d7e-4a6f-f03b-c1b8c739b9ec@myserver.com>' }
GET /activate/a581c7d15cf0e9317e8d0fdf35f9b61587e2bdb9 200 3.236 ms - 12
POST /login 200 402.945 ms - 257
POST /login 200 407.478 ms - 257
POST /login 200 405.072 ms - 257
POST /login 200 404.860 ms - 267
POST /login 200 403.964 ms - 257
07:15:21.53 <INFO> There are 1 players connected
GET /cloudsave/loadfromcloud 200 1.881 ms - 10
POST /cloudsave/savetocloud 200 570.566 ms - -
POST /login 200 405.355 ms - 267
08:02:43.41 <INFO> There are 1 players connected
GET /cloudsave/loadfromcloud 200 2.160 ms - 37192
POST /login 200 404.857 ms - 267
GET /cloudsave/loadfromcloud 403 0.908 ms - 59
GET / 203 0.225 ms - 2
GET / 203 0.175 ms - 2
GET /nice%20ports%2C/Tri%6Eity.txt%2ebak 404 1.314 ms - 174
OPTIONS / 200 0.618 ms - 8
GET / 203 0.171 ms - 2
GET http://clientapi.ipip.net/echo.php?info=20180218204359 404 0.364 ms - 147
GET / 203 0.165 ms - 2
GET / 203 0.157 ms - 2
GET / 203 0.167 ms - 2
GET http://clientapi.ipip.net/echo.php?info=20180221164548 404 0.209 ms - 147
POST /login - - ms - -
POST /login - - ms - -
POST /login - - ms - -
GET / 203 0.175 ms - 2
GET / 203 0.154 ms - 2
GET / 203 0.154 ms - 2
POST /login - - ms - -
POST /login - - ms - -
POST /login - - ms - -
POST /login - - ms - -
POST /login - - ms - -
POST /login - - ms - -
GET /favicon.ico 404 0.200 ms - 150
GET / 203 0.228 ms - 2
GET / 203 0.244 ms - 2
GET / 203 0.358 ms - 2
GET / 203 0.234 ms - 2
GET /wls-wsat/CoordinatorPortType 404 0.231 ms - 167
GET /wls-wsat/RegistrationPortTypeRPC 404 0.200 ms - 171
GET /wls-wsat/ParticipantPortType 404 0.196 ms - 167
GET /wls-wsat/RegistrationRequesterPortType 404 0.209 ms - 177
GET /wls-wsat/CoordinatorPortType11 404 0.230 ms - 169
GET /wls-wsat/RegistrationPortTypeRPC11 404 0.211 ms - 173
GET /wls-wsat/ParticipantPortType11 404 0.214 ms - 169
GET /wls-wsat/RegistrationRequesterPortType11 404 0.212 ms - 179
GET / 203 0.722 ms - 2
GET /favicon.ico 404 0.239 ms - 150
GET / 203 0.245 ms - 2

**Comment by Titanor-Soulstone** [comment]
Here is the clients log so far

/C:/Users/SirTitas/Desktop/MEGA/Telnian%20Legends%20of%20the%20Universe/js/plugins/OrangeGreenworks.js:115 Greenworks failed to load. Make sure you copied all files from the Steamworks SDK to the right folders;
/C:/Users/SirTitas/Desktop/MEGA/Telnian%20Legends%20of%20the%20Universe/js/plugins/OrangeGreenworks.js:116 http://hudell.com/blog/orange-greenworks
/C:/Users/SirTitas/Desktop/MEGA/Telnian%20Legends%20of%20the%20Universe/js/plugins/OrangeGreenworks.js:117 Error
pixi.js:27682 
    PixiJS 4.5.4 - ✰ WebGL ✰      http://www.pixijs.com/    ♥♥♥ 


file:///C:/Users/SirTitas/Desktop/MEGA/Telnian%20Legends%20of%20the%20Universe/fonts/fontawesome-webfont.woff2?v=4.4.0 Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/SirTitas/Desktop/MEGA/Telnian%20Legends%20of%20the%20Universe/fonts/fontawesome-webfont.woff?v=4.4.0 Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/SirTitas/Desktop/MEGA/Telnian%20Legends%20of%20the%20Universe/fonts/fontawesome-webfont.ttf?v=4.4.0 Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by Titanor-Soulstone** [comment]
ok so it now works after updating the clientside to the latest version
