### ISSUE TITLE
Server connection only works in Game Client

### ISSUE THREAD

**Issue by Yoshi72** [Nelderson/MV_Online#7]
When trying to connect with any other browser other than the RPG Maker MV's native client, it blocks the connection due to "Same Originin Policy".

Console Error:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://<IP>:8000/login. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

This still happens, even if you open the index.html directly in the browser.

**Comment by Nelderson** [comment]
So this is not actually a bug, it's just the way RPGMaker interacts when running a local file:// protocol in browsers.  Chrome doesn't load any data, IE just says no as well, Safari generally works, and Firefox will normally load a game this way but any http requests get that error message.

The solution is to deploy your game and host it on a server.  If you have my system running locally you can use my built in static server and put your www folder inside the server/public directory and pointing your browser to localhost:8000/static/www  - You can then use whatever browser you wish with no http request errors :)

**Comment by Yoshi72** [comment]
I'm actually hosting my games via IIS, but it still gives off the same error as the server and the game uses different ports. Apparently there are some ways to get it running via IIS, but it's not worth the effort. In the rare cases I need multiple clients I can just fire up my laptop.

It would still be nice to be able to host the game on a different server (adress) than the server itself. To decrease the server load for example.

**Comment by Nelderson** [comment]
So actually if you have the game hosted on one server and the Online system on a different server it causes this issue.  To fix it add this code below the app.use bodyparser logic in the server.js file and change the url to the ip/website you are running the game from:

```javascript
app.use(function(req,res,next){
	res.setHeader('Access-Control-Allow-Origin', 'http://yourwebsitetoallow.com');
	next();
});
```

**Comment by Yoshi72** [comment]
Works like a charm, thanks! Maybe add a config value to enable this for easier setup? I would assume that it's reasonable to have the game itself being hosted on a different server.

**Comment by Nelderson** [comment]
Honestly most people won't be hosting and running the system on separate servers.  I think it'll just confuse the majority of users if it's a config.  I will however add it to the main documentation so it's easier to come across.
