### ISSUE TITLE
Warning Messages from Server when installed another plugins

### ISSUE THREAD

**Issue by master2015hp** [Nelderson/MV_Online#74]
HI Nelderson,
I installed few another plugins beside of yours (For testing purpose)
When i register a new account, server display this warning message:
"(node:11668) DeprecationWarning: Mongoose: mpromise (mongoose's default promise
library) is deprecated, plug in your own promise library instead: http://mongoos
ejs.com/docs/promises.html"

And then later i login with that account, another warning message show up:
"express deprecated req.param(name): Use req.params, req.body, or req.query instead authenticateAPI.js:7:36"

That seem broken Net Player function, i can no longer see other players (i haven't test GlobalVar yet but i wonder if that broken too?)
This is the plugin list i installed, very few
https://i.imgur.com/NMiuWkG.png
:) thank Nelderson

**Comment by Soubi92** [comment]
The Plugin (MOG_Charaktermotion) overwrite the Game_Player Function "Java" and i think its the Error that you see not other Players.

**Comment by master2015hp** [comment]
No i just checked it, it's because TMJumpAction plugin that broken NetPlayer.
Here is the link of this plugin: http://hikimoki.sakura.ne.jp/plugin/plugin_ja/TMJumpAction.js
Please help me :| what should i do

**Comment by Nelderson** [comment]
These depreciation warnings should be all set :)
