### ISSUE TITLE
BUG  report - Register bug

### ISSUE THREAD

**Issue by master2015hp** [Nelderson/MV_Online#75]
Hi Nelderson, this is the screenshot i took of the bug: https://i.imgur.com/XkJrqbo.png
I tested it in a fresh project with your online plugins only, the project had been confirmed to work normally before i tried to re-create this bug.
Step1: Not start server, try to register a new account, then cancel while it's try connecting
Step2: Start server
Step3: Register an account, then register another account (database has No Account at this moment)
Step4: Change activate value from "false" > "true" for those 2 accounts in mlab database
Step5: Login with the first created account and that will cause the bug

**Comment by Nelderson** [comment]
Check your index.html file for the reference to socket.io and make it's correct.
