### ISSUE TITLE
Online_Network_Players - don't working

### ISSUE THREAD

**Issue by teragotero** [Nelderson/MV_Online#78]
_Hello, I apologize for my bad English, I'm writing through google.
I have a problem, it's a server on AWS, with another computer I go to the game with another account and we do not see each other. I will attach a photo of my plug-ins.
answer please._ 
![image](https://user-images.githubusercontent.com/34458492/39569119-f26b7b26-4ecc-11e8-9175-bf17c435d09f.png)

![image](https://user-images.githubusercontent.com/34458492/39569136-fc5743e0-4ecc-11e8-9dca-629be6fdcb7b.png)

and screen map012, and plugin settngs, Map 002 tried to put 002 (in 2 IDI), in general a lot of things I tried,

**Comment by Nelderson** [comment]
I know for a fact it does work on AWS.   Figure out how to test it locally and see if you're having the same issues.
