### ISSUE TITLE
NonStandard JavaScript

### ISSUE THREAD

**Issue by MChambers1992** [Nelderson/MV_Online#8]
Throughout the code there are a lot of inconsistencies in style to the JavaScript standard as defined here; https://github.com/standard/standard. It might be worth changing this as it would generally improve code readability to other contributors or users. This should actually be pretty trivial to achieve as well due to the number of plugins that will do it automatically in the editor such as this one for Atom; https://atom.io/packages/format-standard. 

I understand this may not be an "official" standard but it is highly recommended by developers to be used as such.

**Comment by Nelderson** [comment]
I'll try it out tonight on my local environment.  The reason for the different styles is because different developers made different sections of this system, but it's not the worst idea to have a basic syntax standard going forward.

**Comment by MChambers1992** [comment]
Yeah I think it'll definitely make it easier for contributors to help development if there is a standard.

**Comment by Nelderson** [comment]
No semicolons....my OCD is going crazy .  RPGMaker uses a bunch of semicolons...

Other than that personal preference I see no other reason not to do this.  I'll consider this the next major update of the overall system.

**Comment by MChambers1992** [comment]
Totally agree with the semicolon point and it would be my preference to keep them as well (C programmer in my day job so not using them feels so alien) but in my mind it's better to follow a standard practise. Looking forward to seeing the code/file style become consistent in the next update.

Feel free to close this issue when the PR is pushed that addresses it. 👍

**Comment by Nelderson** [comment]
Closing, but keeping this in my personal backlog the next major update.
