### ISSUE TITLE
Add Realtime to SERVER

### ISSUE THREAD

**Issue by DatTranPro** [Nelderson/MV_Online#81]
Adds realtime multiplayer functionality to RPG Maker MV, allowing for an "mmo-like" experience.

Realtime multiplayer using Socket.io
Battles are handled in the same scene/map (not a separate battling scene)
Registration and login from remote database
On screen health/mp/level/exp
and more tbh

**Comment by Nelderson** [comment]
Most of that is already here.....and the rest can be done with plugins from the community with the exception of the ABS.  For that......I'm not doing that.
