### ISSUE TITLE
Hi,there's a issue about "io undefined"

### ISSUE THREAD

**Issue by snowwolfjay** [Nelderson/MV_Online#85]
in Online_main_core:
line 70~88:
Game_Network.prototype.connectSocket = function(socket_name, namespace) {
  var url = this._serverURL;
  this._socket[socket_name] = io.connect(url+namespace, {   //there,what this come from
    query: 'token=' + $gameNetwork._token
  });
  var socket = this._socket[socket_name];
  socket.on('connect', function () {
    //Pass token on all POST/GET requests in the header
    $.ajaxSetup({
      headers: {
        'x-access-token': $gameNetwork._token
      }
    });
    console.log('Socket Authenticated');
  });
  socket.on('disconnect', function () {
    console.log('Socket Disconnected');
  });
};

**Comment by snowwolfjay** [comment]
i use a localhost ref of the socket.io.js...changed and solved

**Comment by crynxmartinez** [comment]
How did you solve this bro. I got this error

![image](https://user-images.githubusercontent.com/25003081/47249370-49c0bc80-d445-11e8-9010-a629ffc716db.png)

**Comment by snowwolfjay** [comment]
> How did you solve this bro. I got this error
> 
> ![image](https://user-images.githubusercontent.com/25003081/47249370-49c0bc80-d445-11e8-9010-a629ffc716db.png)

this means fail to load the socket.io.js。
有need you change this file's path in index,html if you serve it or use a cdn link: go https://www.bootcdn.cn/socket.io/ there to find a version of socket.io then copy the cdn link(you can find a free cdn at another site,this is what i use)

**Comment by crynxmartinez** [comment]
copy the cdn link and paste it in my index.html?

right?

**Comment by snowwolfjay** [comment]
> copy the cdn link and paste it in my index.html?
> 
> right?

https://cdn.bootcss.com/socket.io/2.1.0/socket.io.slim.js 有should choose a version. or this version 2.1.0 ,this link can directly use.

**Comment by crynxmartinez** [comment]
Thank you bro!
finally got it to work!!
