### ISSUE TITLE
What happens when you save?

### ISSUE THREAD

**Issue by SapphireGitHub** [Nelderson/MV_Online#87]
Okay, I know this is not a dev question, but just wondering since I will be using the Character Creator EX by SumRndmDde. What happens when you save in a project with this? Will it save online? Will it save on your hard drive? Or will it do nothing?

**Comment by snowwolfjay** [comment]
if you have't rewrithe the savecommand code,it will be local saved.

**Comment by Nelderson** [comment]
Character creation is a whole separate feature that needs to be integrated to work. Save can work as normal or on cloud.  Shouldn't matter
