### ISSUE TITLE
Player stats

### ISSUE THREAD

**Issue by squareware** [Nelderson/MV_Online#93]
Hi Nelderson,

I saw your youtube stream yesterday, nice one.

I have an Idea for players to see each other status: like lvl hp etc when you click on them, like inside a small pop-up box, maybe even with a private chat window?

My idea is to put the stats of the player in a variable. Send that to the database. This is needes so the database holds the save file information apart from the player stats (maybe items).

I'm not sure however how the player data is requested by clicking the player trough the same event (the one that shows the player on the map) so the server should look up the player id from the database for who the data is requested and send it to be shown.

**Comment by Nelderson** [comment]
You can just add to the network players socket plugin to add more info and pass it to other clients.  As for the GUI there are plenty of developers in the community who might be able to help out.

See session 3 video about 2 hours in where I explain the situation :)
