### ISSUE TITLE
Cloud Save bug

### ISSUE THREAD

**Issue by bdnad** [Nelderson/MV_Online#94]
Cloud Save bug
After I saved the game, I quit game. 
Then I added a treasure event on map, 
then deployed game, and replaced all files, then I restarted server, logged in, the treasure box didn't show on map.
I tried NPC event. it didn't show as well.

**Comment by Soubi92** [comment]
You must refresh the map, when you save on a map and reload this map.

When you add new Events etc, the Events show after you change the map. Go ->Out and -> In the Map.
In the Savefiles ( Cloud ) dont Save the "New Events".

i think its help.

**Comment by bdnad** [comment]
ok thank you!
