### ISSUE TITLE
Constantly auto save game

### ISSUE THREAD

**Issue by bdnad** [Nelderson/MV_Online#95]
I am using parallel script to save game every 5 seconds, it works great. However there is one second lag or freezing whenever game is saving. I am wondering if its possible to let the saving process to run in the background or in a way so player wouldn't have to be lagging or freezing while constantly auto saving game every 5 seconds.

**Comment by Nelderson** [comment]
RPGMaker does this synchronously by default.  Look at StorageManager.saveToLocalFile function if you'd like to change it :)
