### ISSUE TITLE
 MV Online Network Players no working

### ISSUE THREAD

**Issue by crodrigr** [Nelderson/MV_Online#96]
Thanks for your contribution. I install plugins about MV Online Network Players, but it does not work for me, I have a mistake with netplayers.js var username = token.name and can not see the two players simultaneously, I thank you for helping me. thank you

**Comment by squareware** [comment]
Maybe it's a bug from the new uploaded files or a different version of MV.
Did you try the old server / plugin and have you followed the tutorials on YT?
Some more info about your config and what you did to the point of the error would be necessary to help you further.

**Comment by crodrigr** [comment]
Thanks

Version rpg 1.6.1
node 8.5.6
npm 5.6.0
 
this error::

C:\Users\camilo\Documents\MV_Online-master\server>npm start

> mvonline@0.2.2 start C:\Users\camilo\Documents\MV_Online-master\server
> node server.js

module.js:540
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\camilo\Documents\MV_Online-master\server\server.js:6:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mvonline@0.2.2 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mvonline@0.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\camilo\AppData\Roaming\npm-cache\_logs\2019-02-10T20_04_37_862Z-debug.log

C:\Users\camilo\Documents\MV_Online-master\server>

**Comment by Nelderson** [comment]
Try pulling the latest version and try it again.  Somehow things got messed up in development the past couple weeks, but I verified network players was working last night with the newest version.

**Comment by crodrigr** [comment]
93/5000
thank you very much for your help Download the latest version but now I get the following error

![image](https://user-images.githubusercontent.com/31961588/52607526-7e1d1600-2e44-11e9-8b38-7125977c6471.png)

**Comment by squareware** [comment]
I think your redis server is not running?

try in a different console: npm start redis-server or something to get it going and then
try the mv online server to start.

**Comment by Nelderson** [comment]
I agree.  Redis isn't running.

**Comment by rafaelrodrigosilveira** [comment]
I think that you have put in readme file, the mv online operation system and others requirements. How the npm version, and others needed requirements. It s help us to create the good server to works. Thank you Guys.
