### ISSUE TITLE
Can't connect to MongoDB

### ISSUE THREAD

**Issue by TybaIt** [Nelderson/MV_Online#98]
For some reason I cannot connect to MongoDB. 

I have created a fresh account on mongo DB with a static unchangable usewrname that is my email adress. 
I have put the email adress as usernamer and the password in the server/configurations/config.js
  mongoDBconnect: process.env.MV_MONGO_URI || 'mongodb://username:password@linktomongodb.com:39504/collection' 

but it won't connect.

Error log:
12:29:03.84 <ERROR> { MongoNetworkError: failed to connect to server [linktomongodb.com:39504] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND linktomongodb.com linktomongodb.com:39504]
    at Pool.<anonymous> (F:\Git\MV_Online\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)

I have tried an url encoded @-sign for the email adress that is the username %40 and also &#64; 

It won't connect. Any help is appreciated.

**Comment by squareware** [comment]
I think your 'linktomongodb.com' need to be changes to localhost if you configured mongo on your nodejs server or at least change it to a real server adress where the mongo db is hosted.
Like mlabs was it? it is shown in one of the tutorials and should work.

 mongoDBconnect: 'mongodb://[username]:[password]@[serveradress.com]:[portnumber]/[dbname]

**Comment by Nelderson** [comment]
@squareware ty for the assist point good sir.
